### ISSUE TITLE
How to use hackpad to synchronise with github

### ISSUE THREAD

**Issue by lesteve** [lesteve/scikit-learn-tutorial#12]
cc @GaelVaroquaux

Top right, click on the `...` icon then "versions":
![image](https://user-images.githubusercontent.com/1680079/67968654-12fcb500-fc08-11e9-93ee-146fce7a577d.png)

A modal appears, the name of the github file is shown on the top left (`lesteve/scikit-learn/plan.md`) and then on the right hand side the down/up arrows can pull/push to github.
![image](https://user-images.githubusercontent.com/1680079/67968747-3aec1880-fc08-11e9-85e4-f585de9d4f9c.png)

Any troubles with that let me know!

**Comment by GaelVaroquaux** [comment]
Indeed, I get this too. I hadn't found it sorry.

OK, let's synchronize after we merge my PR.

**Comment by lesteve** [comment]
No worries (the interface is not super intuitive). It may be useful as a reference for later anwyay (even for me if I forget).
