### ISSUE TITLE
RFC Stop pushing the rendered notebook in the main repo?

### ISSUE THREAD

**Issue by ogrisel** [lesteve/scikit-learn-tutorial#5]
Maybe instead we could have a CI job that check that the notebook render without errors and another CI jobs that run the rendering of the notebooks only on merge commits in master and commits and push the results into a dedicated "rendered" branch that we then use for nbviewer links. We could also render the HTML to make the rendered notebooks directly browsable as a website on https://lesteve.github.io/scikit-learn-tutorial

This way we would never have the diff with spurious output changes in pull request.

WDYT?

**Comment by glemaitre** [comment]
I am +1.

Also, we can easily get changes in the metadata depending on the local version. We could only push python files and make the conversion to both notebooks and rendered notebooks using CIs.

This might limit unattended diff due to versioning.

**Comment by ogrisel** [comment]
I think I prefer having the (non-rendered) notebooks up to date in the master branch of the repo. Having a CI bot automatically commit in PR or master branches would be weird.

**Comment by lesteve** [comment]
It is nice to be able the rendered notebook in the PR to use ReviewNB to review the rendered notebook.

An alternative would be to render the notebook in our CI and have a html artifact (like we do for scikit-learn doc build inside a PR). ReviewNB allows you to comment inside notebooks so this is a bit more convenient than commenting on the `.py` file about some visual thing in the html.

IIRC in our discussion we agreed the following:
* keep it like it is for now and reevaluate in the future
* if the repo starts growing to big, we could try git tricks, to erase the some part of the history or maybe (if possible) the history of the `rendered_notebooks` folder.

I am going to close this one, but feel free to reopen at some point in the future.
